name: Deploy Quartz site to GitHub Pages

on:
  push:
    paths:
      - '**/*.md'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout notes repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for git info

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}

      - name: Clone Quartz repository
        run: git clone git@github.com:avvero/devirium-quartz.git quartz

      - name: Clone content repository
        run: git clone git@github.com:avvero/devirium.git quartz_content

      - name: Clear Quartz content directory
        run: rm -rf quartz/content/*

      - name: Copy content to Quartz
        run: cp -r quartz_content/* quartz/content/

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Clear Node.js cache
        run: npm cache clean --force

      - name: Install Dependencies
        run: |
          cd quartz
          npm ci

      - name: Build Quartz
        run: |
          cd quartz
          npx quartz build

      - name: Append Query Strings to Assets
        run: |
          node -e "
          const fs = require('fs');
          const path = require('path');
          function appendQueryStrings(filePath, version) {
            const content = fs.readFileSync(filePath, 'utf8');
            const updatedContent = content.replace(/(\.css|\.js)\"/g, `$1?v=${version}\"`);
            fs.writeFileSync(filePath, updatedContent, 'utf8');
          }
          const publicDir = path.join(__dirname, 'quartz', 'public');
          const version = Date.now();
          fs.readdirSync(publicDir).forEach(file => {
            const filePath = path.join(publicDir, file);
            if (fs.lstatSync(filePath).isFile()) {
              appendQueryStrings(filePath, version);
            }
          });
          "

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: quartz/public

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          headers: |
            /index.html Cache-Control: no-cache
            /assets/* Cache-Control: max-age=31536000
