# .github/workflows/send_notes.yml
name: Send Notes on Commit

on:
  push:
    paths:
      - '**/*.md'

jobs:
  send-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          separator: ","

      - name: List all changed files
        run: |
          echo "${{ steps.changed-files.outputs.all_changed_files }}" | jq -R 'split(",") | .[]' > changed_files.json
          cat changed_files.json
          while IFS= read -r file; do
            decoded_file=$(echo "$file" | jq -r @base64 --decode)
            echo "Changed file: $decoded_file"
          done < changed_files.json
