# .github/workflows/send_notes.yml
name: Send Notes on Commit

on:
  push:
    paths:
      - '**/*.md'

jobs:
  send-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          separator: ","

      - name: List all changed files
        run: |
          changed_files="${{ steps.changed-files.outputs.all_changed_files }}"
          echo "$changed_files" | tr ',' '\n' > changed_files.txt
          readarray -t files < changed_files.txt
          for file in "${files[@]}"; do
            echo "Changed file: $file"
          done
