# .github/workflows/send_notes.yml
name: Send Notes on Commit

on:
  push:
    paths:
      - '**/*.md'

jobs:
  send-notes:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: List changed files
        run: |
          git diff --name-only HEAD^ HEAD -- '*.md' > changed_files.txt
          cat changed_files.txt