# .github/workflows/send_notes.yml
name: Send Notes on Commit

on:
  push:
    paths:
      - '**/*.md'

jobs:
  send_notes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Debug commit info
      run: |
        echo "Current commit SHA: $GITHUB_SHA"
        echo "Previous commit SHA: ${{ github.event.before }}"
        git log --oneline -2

    - name: Get changed markdown files
      id: changed_files
      run: |
        if [ $(git rev-list --count HEAD) -eq 1 ]; then
          echo "First commit detected."
          FILES=$(git diff-tree --no-commit-id --name-only -r HEAD -- '*.md')
        else
          echo "Subsequent commit detected."
          FILES=$(git diff --name-only ${{ github.event.before }} HEAD -- '*.md')
        fi
        echo "Changed files: $FILES"
        echo "FILES=$FILES" >> $GITHUB_ENV

    - name: Print changed files from env
      run: |
        echo "Files from env: ${{ env.FILES }}"

    - name: Send notes to server
      env:
        FILES: ${{ env.FILES }}
      run: |
        if [ -n "$FILES" ]; then
          json_data="{\"notes\":["
          for file in $FILES;
