# .github/workflows/send_notes.yml
name: Send Notes on Commit

on:
  push:
    paths:
      - '**/*.md'

jobs:
  send_notes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get changed markdown files
      id: changed_files
      run: |
        if [ $(git rev-list --count HEAD) -eq 1 ]; then
          FILES=$(git ls-tree --name-only -r HEAD -- '*.md')
        else
          FILES=$(git diff --name-only HEAD~1 HEAD -- '*.md')
        fi
        echo "Changed files: $FILES"
        echo "FILES=$FILES" >> $GITHUB_ENV

    - name: Send notes to server
      env:
        FILES: ${{ env.FILES }}
      run: |
        if [ -n "$FILES" ]; then
          json_data="{\"notes\":["
          for file in $FILES; do
            content=$(cat "$file" | jq -sR .)
            json_data="$json_data{\"file\":\"$file\",\"content\":$content},"
          done
          json_data="${json_data%,}]}"
          echo "JSON Data: $json_data"
          response=$(curl -s -o /dev/null -w "%{http_code}" -H "Content-Type: application/json" -X POST -d "$json_data" http://your-server-ip:5000/receive_notes)
          echo "Server response: $response"
          if [ "$response" -ne 200 ]; then
            echo "Failed to send notes to server"
            exit 1
          fi
        fi
