# .github/workflows/send_notes.yml
name: Send Notes on Commit

on:
  push:
    paths:
      - '**/*.md'

jobs:
  send-notes:
    runs-on: ubuntu-latest  # windows-latest || macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v4

      # -----------------------------------------------------------------------------------------------------------
      # Example 1
      # -----------------------------------------------------------------------------------------------------------
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          separator: ","

      - name: List all changed files
        run: |
          IFS=$',' read -a MODIFIED_FILES_ARRAY <<< "${{ steps.changed-files.outputs.all_changed_files }}"
          for file in "${MODIFIED_FILES_ARRAY[@]}"; do
            echo $file
          done
        shell:
          bash