# .github/workflows/send_notes.yml
name: Send Notes on Commit

on:
  push:
    paths:
      - '**/*.md'

jobs:
  send-notes:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: List and display changed files
        run: |
          #!/bin/bash

          # Get the list of changed files
          if git rev-parse HEAD~1 >/dev/null 2>&1; then
            git diff --name-only -z HEAD~1 HEAD -- '*.md' > changed_files.txt
          else
            git ls-tree --name-only -r -z HEAD -- '*.md' > changed_files.txt
          fi

          # Display file names and contents using git show
          while IFS= read -r -d '' file; do
            if [[ -n "$file" ]]; then
              echo "File: $file"
              echo "Content:"
              git show "HEAD:$file"
              echo ""
            fi
          done < changed_files.txt
