# .github/workflows/send_notes.yml
name: Send Notes on Commit

on:
  push:
    paths:
      - '**/*.md'

jobs:
  send-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          separator: ","

      - name: List all changed files
        run: |
          echo "${{ steps.changed-files.outputs.all_changed_files }}" | tr ',' '\n' > changed_files.txt
          cat changed_files.txt

      - name: Send notes to server
        env:
          SEND_NOTES_URL: ${{ secrets.SEND_NOTES_URL }}
        run: |
          while IFS= read -r file; do
            content=$(cat "$file" | jq -sR .)
            json_data="{\"content\":$content}"
            echo "JSON Data: $json_data"
            response=$(curl -s -o /dev/null -w "%{http_code}" -H "Content-Type: application/json" -X POST -d "$json_data" $SEND_NOTES_URL)
            echo "Server response: $response"
            if [ "$response" -ne 200 ]; then
              echo "Failed to send notes to server for file $file. Response code: $response"
              exit 1
            fi
          done < changed_files.txt
