# .github/workflows/send_notes.yml
name: Send Notes on Commit

on:
  push:
    paths:
      - '**/*.md'

jobs:
  send_notes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Debug commit info
      run: |
        echo "Current commit SHA: $GITHUB_SHA"
        PREV_SHA=$(git rev-parse HEAD~1 2>/dev/null || echo "")
        if [ -z "$PREV_SHA" ]; then
          echo "No previous commit found, this is likely the first commit."
        else
          echo "Previous commit SHA: $PREV_SHA"
        fi
        git log --oneline -2 || true

    - name: Get changed markdown files
      id: changed_files
      run: |
        if [ -z "$PREV_SHA" ]; then
          FILES=$(git ls-tree -r HEAD --name-only | grep '\.md$' | tr '\n' ' ')
        else
          FILES=$(git diff --name-only $PREV_SHA HEAD | grep '\.md$' | tr '\n' ' ')
        fi
        echo "Changed markdown files: $FILES"
        echo "FILES=$FILES" >> $GITHUB_ENV

    - name: Print changed files from env
      run: |
        echo "Files from env: ${{ env.FILES }}"

    - name: Send notes to server
      env:
        FILES: ${{ env.FILES }}
      run: |
        if [ -n "$FILES" ]; then
          json_data="{\"notes\":["
          for file in $FILES; do
            content=$(cat "$file" | jq -sR .)
            json_data="$json_data{\"file\":\"$file\",\"content\":$content},"
          done
          json_data="${json_data%,}]}"
          echo "JSON Data: $json_data"
          
          # Additional debugging information
          echo "Executing curl command"
          curl -v -H "Content-Type: application/json" -X POST -d "$json_data" http://your-server-ip:5000/receive_notes

          response=$(curl -s -o /dev/null -w "%{http_code}" -H "Content-Type: application/json" -X POST -d "$json_data" http://your-server-ip:5000/receive_notes)
          echo "Server response: $response"
          if [ "$response" -ne 200 ]; then
            echo "Failed to send notes to server. Response code: $response"
            exit 1
          fi
        else
          echo "No markdown files changed"
        fi
