# .github/workflows/send_notes.yml
name: Send Notes on Commit

on:
  push:
    paths:
      - '**/*.md'

jobs:
  send-notes:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: List and send changed files
        env:
          SEND_NOTES_URL: ${{ secrets.SEND_NOTES_URL }}
        run: |
          #!/bin/bash

          # Get the list of changed files
          if git rev-parse HEAD~1 >/dev/null 2>&1; then
            git diff --name-only -z --diff-filter=ACM HEAD~1 HEAD -- '*.md' > changed_files.txt
          else
            git ls-tree --name-only -r -z HEAD -- '*.md' > changed_files.txt
          fi

          # Display file names and send contents using curl
          while IFS= read -r -d '' file; do
            if [[ -n "$file" ]]; then
              echo "File: $file"
              echo "Content:"
              content=$(git show "HEAD:$file" | jq -sR .)
              json_data="{\"file\":\"$file\",\"content\":$content}"
              echo "JSON Data: $json_data"
              response=$(curl -s -o /dev/null -w "%{http_code}" -H "Content-Type: application/json" -X POST -d "$json_data" $SEND_NOTES_URL)
              echo "Server response: $response"
              if [ "$response" -ne 200 ]; then
                echo "Failed to send notes to server for file $file. Response code: $response"
                exit 1
              fi
              echo ""
            fi
          done < changed_files.txt
