# .github/workflows/send_notes.yml
name: Send Notes on Commit

on:
  push:
    paths:
      - '**/*.md'

jobs:
  send_notes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get all changed markdown files
      id: changed-markdown-files
      uses: tj-actions/changed-files@v44
      with:
        files: |
          **.md

    - name: List all changed markdown files
      if: steps.changed-markdown-files.outputs.any_changed == 'true'
      run: |
        echo "Changed markdown files:"
        echo "${{ steps.changed-markdown-files.outputs.all_changed_files }}"

    - name: Send notes to server
      if: steps.changed-markdown-files.outputs.any_changed == 'true'
      env:
        ALL_CHANGED_FILES: ${{ steps.changed-markdown-files.outputs.all_changed_files }}
        SEND_NOTES_URL: ${{ secrets.SEND_NOTES_URL }}
      run: |
        IFS=$'\n' read -d '' -r -a files <<< "${ALL_CHANGED_FILES}"
        for file in "${files[@]}"; do
          content=$(cat "$file" | base64)
          file_encoded=$(echo "$file" | base64)
          json_data="{\"file\":\"$file_encoded\",\"content\":\"$content\"}"
          echo "JSON Data: $json_data"
          response=$(curl -s -o /dev/null -w "%{http_code}" -H "Content-Type: application/json" -X POST -d "$json_data" $SEND_NOTES_URL)
          echo "Server response: $response"
          if [ "$response" -ne 200 ]; then
            echo "Failed to send notes to server for file $file. Response code: $response"
            exit 1
          fi
        done
