name: Send Notes on Commit

on:
  push:
    paths:
      - '**/*.md'

jobs:
  send-notes:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.16'

      - name: List and send changed files
        env:
          SEND_NOTES_URL: ${{ secrets.SEND_NOTES_URL }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          #!/bin/bash

          set -e

          send_telegram_message() {
            local message=$1
            curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage" \
              -H "Content-Type: application/json" \
              -d "{\"chat_id\":\"$TELEGRAM_CHAT_ID\", \"text\":\"$message\"}" > /dev/null
          }

          # Get the list of changed files
          if git rev-parse HEAD~1 >/dev/null 2>&1; then
            git diff --name-only -z --diff-filter=ACM HEAD~1 HEAD -- '*.md' > changed_files.txt
          else
            git ls-tree --name-only -r -z HEAD -- '*.md' > changed_files.txt
          fi

          # Compile the Go script
          echo "Compiling find-links.go"
          go build -o find-links find-links.go || { send_telegram_message "Failed to compile find-links.go"; exit 1; }

          # Display file names and send contents using curl
          while IFS= read -r -d '' file; do
            if [[ -n "$file" ]]; then
              echo "Processing file: $file"
              content=$(git show "HEAD:$file" | jq -sR .)
              links=$(./find-links "$file") || { send_telegram_message "Error processing file $file with find-links.go"; exit 1; }

              json_data="{\"file\":\"$file\",\"content\":$content, \"links\": $links}"

              echo "JSON Data: $json_data"
              response=$(curl -s -o /dev/null -w "%{http_code}" -H "Content-Type: application/json" -X POST -d "$json_data" $SEND_NOTES_URL)
              echo "Server response: $response"
              if [ "$response" -ne 200 ]; then
                message="Failed to send notes to server for file $file. Response code: $response"
                echo "$message"
                send_telegram_message "$message"
                exit 1
              fi
              echo ""
            fi
          done < changed_files.txt
